---
- name: create containers in separate pods 
  hosts: "*pod-aut*"

  tasks: 
  - name: instantiate the DB container
    containers.podman.podman_container:
      name: quarkus_test
      state: started
      image: registry.redhat.io/rhel8/postgresql-12
      auto_remove: yes
      detach: yes
      env:
        POSTGRESQL_USER: "quarkus_test"
        POSTGRESQL_PASSWORD: "quarkus_test"
        POSTGRESQL_DATABASE: "quarkus_test"
        POSTGRESQL_SERVICE_HOST: "{{ ansible_default_ipv4.address }}"
      ports:
        - "5432:5432"

  - name: instantiate the nodejs container
    containers.podman.podman_container:
      name: nodejs_test
      state: started
      image: quay.io/rbaumgar/nodejs-postgresql-persistent
      auto_remove: yes
      detach: yes
      env:
        POSTGRESQL_USER: "quarkus_test"
        POSTGRESQL_PASSWORD: "quarkus_test"
        POSTGRESQL_DATABASE: "quarkus_test"
        POSTGRESQL_SERVICE_HOST: "{{ ansible_default_ipv4.address }}"
      ports:
        - "8080:8080"

