---
- name: UseCase1 standalone containers
  hosts: "*pod-aut*"
  vars_files:
  - /home/ansible/vault-auth.yml

  collections: 
    - kvegh.podman_autodemo
  roles: 
    - clean_env
    - prep_env
    - usecase1_rootless_containers_in_separate_pods

