---
- name: usecase4: kube yaml replay
  hosts: "*pod-aut*"
  # moved vault data to controller custom creds and -e paramters to navigator. This section can be removed in the future if that worked. 
  # vars_files:
  # - /home/ansible/vault-auth.yml
  become: yes
  vars:
    counter: 10

  collections: 
    - kvegh.podman_autodemo
  roles: 
    - clean_env
    - prep_env
    - usecase4_kube_yaml_replay

