---
- name: login and pull images
  hosts: "*pod-aut*"
  vars_files:
  - /home/ansible/vault-auth.yml

  collections: 
    - kvegh.podman_autodemo
  roles: 
    - clean_env
    - prep_env
    - usecase2_rootless_containers_within_same_pod

