---
# tasks file for prep_env

- name: Ensuring PODMAN is installed 
  package: 
    name: podman 
    state: present 
  become: yes

- name: LOGIN to container repo registry.redhat.io
  containers.podman.podman_login:
    username: kvegh@redhat.com
    password: "{{ access_password }}" 
    registry: registry.redhat.io

- name: LOGIN to container repo QUAY.io 
  containers.podman.podman_login:
    username: kvegh
    password: "{{ quay_password }}" 
    registry: quay.io

- name: PULL UBI images
  containers.podman.podman_image:
    name: registry.access.redhat.com/ubi8-minimal
    state: present

- name: PULL Red Hat Postgres 12  images
  containers.podman.podman_image:
    name: registry.redhat.io/rhel8/postgresql-12:latest
    state: present

- name: PULL Bob's postgres12 image
  containers.podman.podman_image:
    name: quay.io/rbaumgar/nodejs-postgresql-persistent
    state: present

- name: enable FW service
  service: 
    name: firewalld
    state: started
    enabled: true
  become: true

- name: Allow port 8080 fw settings
  ansible.posix.firewalld: 
    port: 8080/tcp
    permanent: yes
    immediate: yes
    state: enabled 
  become: yes
